### ISSUE TITLE
Laboratory Work #0

### ISSUE THREAD

**Issue by bpai201** [OS-IS/ai-201-pryymak#1]

**Comment by bpai201** [comment]
5 Клонування GitHub-репозиторію
Клонувати GitHub-репозиторій на локальний комп`ютер без використання процесу
автентифікації.
Зробити знімок екрану результатів виконання завдання та розмістити його у файлі
графічного формату як коментар до Issue.

<img width="1099" alt="image" src="https://github.com/user-attachments/assets/c09c7650-0f8f-48ef-9bfa-5ae6ae55f6b2">

**Comment by bpai201** [comment]
8.2 Оновити GitHub-репозиторій зі змінами з локального Git-репозиторія,
використовуючи Token. Замість імені GitHub-користувача вказати назву GitHub-організації,
де створено GitHub-репозиторій, наприклад, OS-IS.

3
Зробити знімок екрану результатів виконання завдання та розмістити його у файлі
графічного формату як коментар до Issue.

<img width="576" alt="image" src="https://github.com/user-attachments/assets/05cb7ba8-5739-46ee-9f9d-5fd0b91f0e36">

**Comment by bpai201** [comment]
10 Безпечна робота з GitHub-репозиторієм через SSH-ключі

10.1 Створити SSH-ключі та розташувати створений відкритий ключ у GitHub-
репозиторії. Подробиці в документі [2] списку літератури.

Зробити знімок екрану результатів виконання завдання та розмістити його у файлі
графічного формату як коментар до Issue.

<img width="1289" alt="image" src="https://github.com/user-attachments/assets/52298151-9471-4e6e-b2d1-77b243d378ff">

**Comment by bpai201** [comment]
10.3 Повторно клонувати GitHub-репозиторій на локальний комп`ютер, але вже з
використанням SSH-ключів.
Зробити знімок екрану результатів виконання завдання та розмістити його у файлі
графічного формату як коментар до Issue.
<img width="830" alt="image" src="https://github.com/user-attachments/assets/cc6b6738-1111-4735-b91f-24630ec0fd9b">

**Comment by oleksandrblazhko** [comment]
Рішення прийнято.
5 балів
